// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketingSystem.Common.Context;

#nullable disable

namespace TicketingSystem.MigrationService.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    partial class TicketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartTicket", b =>
                {
                    b.Property<int>("CartsCartId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketsTicketId")
                        .HasColumnType("integer");

                    b.HasKey("CartsCartId", "TicketsTicketId");

                    b.HasIndex("TicketsTicketId");

                    b.ToTable("CartTicket");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<int>("CartStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("CartId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CartStatus = 1,
                            PaymentId = 1,
                            PersonId = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.CartStatusRow", b =>
                {
                    b.Property<int>("CartStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CartStatusId");

                    b.ToTable("CartStatuses");

                    b.HasData(
                        new
                        {
                            CartStatusId = 0,
                            Status = "NotPayed"
                        },
                        new
                        {
                            CartStatusId = 1,
                            Status = "Payed"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.CartTicket", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("CartId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("CartsTickets");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            TicketId = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Date = new DateTime(2024, 12, 30, 19, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Новогодний спектакль",
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            PaymentTime = new DateTime(2024, 11, 30, 19, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            ContactInfo = "testContact",
                            Name = "Юрий"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.PriceCategory", b =>
                {
                    b.Property<int>("PriceCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceCategoryId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("PriceCategoryDescription")
                        .HasColumnType("text");

                    b.Property<string>("PriceCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PriceUsd")
                        .HasColumnType("real");

                    b.HasKey("PriceCategoryId");

                    b.HasIndex("EventId");

                    b.ToTable("PriceCategories");

                    b.HasData(
                        new
                        {
                            PriceCategoryId = 1,
                            EventId = 1,
                            PriceCategoryName = "Normal seat",
                            PriceUsd = 10f
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeatId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("PriceCategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeatType")
                        .HasColumnType("integer");

                    b.Property<int?>("SectionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SeatId");

                    b.HasIndex("EventId");

                    b.HasIndex("PriceCategoryId");

                    b.HasIndex("SectionId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            EventId = 1,
                            RowNumber = 1,
                            SeatType = 0,
                            SectionId = 1,
                            Status = 2
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.SeatStatusRow", b =>
                {
                    b.Property<int>("SeatStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SeatStatusId");

                    b.ToTable("SeatStatuses");

                    b.HasData(
                        new
                        {
                            SeatStatusId = 0,
                            Status = "Free"
                        },
                        new
                        {
                            SeatStatusId = 1,
                            Status = "Booked"
                        },
                        new
                        {
                            SeatStatusId = 2,
                            Status = "Purchased"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.SeatTypeRow", b =>
                {
                    b.Property<int>("SeatTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SeatTypeId");

                    b.ToTable("SeatTypes");

                    b.HasData(
                        new
                        {
                            SeatTypeId = 0,
                            SeatType = "DesignatedSeat"
                        },
                        new
                        {
                            SeatTypeId = 1,
                            SeatType = "GeneralAdmission"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionId"));

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("SectionId");

                    b.HasIndex("VenueId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionId = 1,
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("PriceCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer");

                    b.HasKey("TicketId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PriceCategoryId");

                    b.HasIndex("SeatId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            EventId = 1,
                            PersonId = 1,
                            PriceCategoryId = 1,
                            SeatId = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "ул. Зарафшан, 28",
                            Name = "Большой театр Навои"
                        });
                });

            modelBuilder.Entity("CartTicket", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartsCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Cart", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Payment", "Payment")
                        .WithOne("Cart")
                        .HasForeignKey("TicketingSystem.Common.Model.Database.Entities.Cart", "PaymentId");

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.CartTicket", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Event", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.PriceCategory", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Seat", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.PriceCategory", null)
                        .WithMany("Seats")
                        .HasForeignKey("PriceCategoryId");

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Section", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SectionId");

                    b.Navigation("Event");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Section", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Venue", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Ticket", b =>
                {
                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Person", "Person")
                        .WithMany("Tickets")
                        .HasForeignKey("PersonId");

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.PriceCategory", "PriceCategory")
                        .WithMany()
                        .HasForeignKey("PriceCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystem.Common.Model.Database.Entities.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Person");

                    b.Navigation("PriceCategory");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Payment", b =>
                {
                    b.Navigation("Cart");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Person", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.PriceCategory", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Section", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketingSystem.Common.Model.Database.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
